#ifndef LITTLE_BOTS_INSTANTIATES
#define LITTLE_BOTS_INSTANTIATES

//Motor left_motor(&pololu_motor_serial_port, POLOLU_LEFT_MOTOR_RESET_PIN, POLOLU_LEFT_MOTOR_ERROR_PIN);
Motor right_motor(POLOLU_RIGHT_MOTOR_RESET_PIN, POLOLU_RIGHT_MOTOR_ERROR_PIN);

#endif // LITTLE_BOTS_INSTANTIATES


